import { AINewsItem, TrendItem, StatsData } from "./types"

export const mockStats: StatsData = {
  totalNews: 1247,
  weeklyNews: 89,
  overseasRatio: 72,
  productReleases: 156,
}

export const mockNewsItems: AINewsItem[] = [
  {
    id: "1",
    title: "OpenAI 发布 GPT-5 模型，推理能力大幅提升",
    publisher: "OpenAI",
    date: "2026-04-15",
    region: "海外",
    type: "产品发布",
    source: "OpenAI 官方博客",
    sourceType: "官方公告",
    summary: "新一代大语言模型在复杂推理、代码生成和多模态理解方面取得重大突破，性能较前代提升40%。",
    tags: ["GPT-5", "大模型", "推理能力", "多模态"],
    trackingValue: "关注大模型能力边界突破，可能重塑行业竞争格局，对企业AI战略有重要参考价值。",
    originalUrl: "https://openai.com/blog/gpt-5",
  },
  {
    id: "2",
    title: "Anthropic Claude 4 发布，强调AI安全与对齐",
    publisher: "Anthropic",
    date: "2026-04-14",
    region: "海外",
    type: "产品发布",
    source: "Anthropic 官网",
    sourceType: "官方公告",
    summary: "Claude 4在保持高性能的同时，大幅提升了安全性和可控性，支持企业级部署。",
    tags: ["Claude", "AI安全", "企业级", "对齐技术"],
    trackingValue: "安全可控的AI对企业采购决策影响重大，是差异化竞争的关键因素。",
    originalUrl: "https://anthropic.com/claude-4",
  },
  {
    id: "3",
    title: "Google DeepMind 推出 Gemini Ultra 2.0",
    publisher: "Google DeepMind",
    date: "2026-04-13",
    region: "海外",
    type: "功能更新",
    source: "Google AI Blog",
    sourceType: "官方公告",
    summary: "Gemini Ultra 2.0 在科学推理和代码生成领域表现突出，支持百万级上下文窗口。",
    tags: ["Gemini", "Google", "长上下文", "科学推理"],
    trackingValue: "长上下文能力是企业知识管理和文档处理的关键技术，值得重点关注。",
    originalUrl: "https://deepmind.google/gemini",
  },
  {
    id: "4",
    title: "百度文心一言 5.0 发布，中文理解能力领先",
    publisher: "百度",
    date: "2026-04-12",
    region: "国内",
    type: "产品发布",
    source: "百度AI开放平台",
    sourceType: "官方公告",
    summary: "文心一言5.0在中文场景下表现优异，针对企业办公、客服等场景进行深度优化。",
    tags: ["文心一言", "百度", "中文大模型", "企业应用"],
    trackingValue: "国产大模型在中文场景的差异化优势，对本土企业有重要参考意义。",
    originalUrl: "https://yiyan.baidu.com",
  },
  {
    id: "5",
    title: "Microsoft Copilot 全面整合 GPT-5 能力",
    publisher: "Microsoft",
    date: "2026-04-11",
    region: "海外",
    type: "功能更新",
    source: "Microsoft 365 Blog",
    sourceType: "官方公告",
    summary: "Microsoft 365 Copilot 整合最新GPT-5能力，办公自动化水平再上新台阶。",
    tags: ["Copilot", "Microsoft", "办公自动化", "GPT-5"],
    trackingValue: "办公场景AI化是企业数字化转型的核心方向，具有广泛商业价值。",
    originalUrl: "https://microsoft.com/copilot",
  },
  {
    id: "6",
    title: "Meta 开源 Llama 4，支持商业使用",
    publisher: "Meta",
    date: "2026-04-10",
    region: "海外",
    type: "产品发布",
    source: "Meta AI Research",
    sourceType: "官方公告",
    summary: "Llama 4 以开源方式发布，性能接近闭源顶级模型，支持商业化部署。",
    tags: ["Llama", "开源", "Meta", "商业授权"],
    trackingValue: "开源大模型降低了企业AI应用门槛，对中小企业战略选择有重要影响。",
    originalUrl: "https://ai.meta.com/llama",
  },
  {
    id: "7",
    title: "阿里通义千问发布Agent开发平台",
    publisher: "阿里云",
    date: "2026-04-09",
    region: "国内",
    type: "功能更新",
    source: "阿里云官网",
    sourceType: "官方公告",
    summary: "通义千问推出低代码Agent开发平台，支持企业快速构建AI应用。",
    tags: ["通义千问", "Agent", "低代码", "阿里云"],
    trackingValue: "Agent开发平台降低AI应用开发门槛，是2026年AI产品的重要趋势。",
    originalUrl: "https://tongyi.aliyun.com",
  },
  {
    id: "8",
    title: "Midjourney V7 支持实时图像编辑",
    publisher: "Midjourney",
    date: "2026-04-08",
    region: "海外",
    type: "功能更新",
    source: "Discord 官方频道",
    sourceType: "社交媒体",
    summary: "Midjourney V7 新增实时图像编辑功能，支持自然语言精准控制图像生成。",
    tags: ["Midjourney", "图像生成", "实时编辑", "多模态"],
    trackingValue: "图像生成技术的可控性提升，对设计、营销等领域有直接商业价值。",
    originalUrl: "https://midjourney.com",
  },
]

export const mockTrends: TrendItem[] = [
  {
    id: "1",
    title: "Agent 生态加速成熟",
    description: "各大厂商纷纷推出Agent开发平台，AI应用从单轮对话向自主任务执行演进，企业级Agent应用场景快速落地。",
    hotLevel: "高",
    relatedProducts: ["GPT-5", "Claude 4", "通义千问"],
  },
  {
    id: "2",
    title: "多模态能力成标配",
    description: "图文理解、视频生成等多模态能力已成为主流大模型标配，推动内容创作和分析场景全面升级。",
    hotLevel: "高",
    relatedProducts: ["Gemini", "GPT-5", "文心一言"],
  },
  {
    id: "3",
    title: "开源与闭源竞争加剧",
    description: "Llama 4等开源模型性能逼近闭源产品，企业在AI选型中面临更多技术路线选择。",
    hotLevel: "中",
    relatedProducts: ["Llama 4", "Qwen", "Mistral"],
  },
  {
    id: "4",
    title: "AI安全合规受关注",
    description: "随着AI应用深入企业核心业务，数据安全、隐私保护和AI治理成为采购决策的重要考量因素。",
    hotLevel: "中",
    relatedProducts: ["Claude 4", "Azure OpenAI", "华为盘古"],
  },
]
